### ISSUE TITLE
Warning: Hash#index is deprecated; use Hash#key

### ISSUE THREAD

**Issue by ulrik** [ryanlntn/medic#6]
I think this warning comes due to line 80 and 83 in lib/medic/finders.rb 

h[:sample_type] = Medic::Types::TYPE_IDENTIFIERS.index(sample.sampleType.identifier)
and 
h[:category_type] = Medic::Types::TYPE_IDENTIFIERS.index(sample.categoryType.identifier)

I am in RubyMotion version 4.11

**Comment by ryanlntn** [comment]
Thanks @ulrik! This is updated on master.
